refactor: Character 코드 리팩토링 및 테스트 코드 작성
software-maestro-starting-blue/fourtoon-cookie-backend pull request #10
Opened 2024-07-21 07:28 UTC by minseojo

# [refactor] 제목
### Pull Request 타입
- [ ] bug (버그수정)
- [ ] feat (기능)
- [ ] style (코드 스타일 수정)
- [x] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-212
---

#### 구현 내용
- 필요 없는 calendarThumbnailUrl 필드 제거
- 모든 캐릭터를 가져오는 코드 변경 -> 모델 타입에 맞는 캐릭터 가져오기

- 테스트 코드 작성
    - findAllByModelType: 특정 모델 타입의 모든 캐릭터를 가져온다.

2024-07-22 02:09 UTC, JuneBridge03 requested changes
캐릭터 로직에 대한 적절한 리팩토링을 해주시고, 테스트 코드도 작성해주셔서 감사합니다!

일부 의견을 작성하였으니 한번 확인해보시면 감사할 듯 합니다!

2024-07-22 02:09 UTC, JuneBridge03 commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterRepositoryTest.java
> +    }
실패 테스트 코드도 작성해야 할 것 같다고 생각합니다..!

ex. 어떤 캐릭터를 찾을 수 없는 경우

2024-07-22 02:09 UTC, JuneBridge03 commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterRepositoryTest.java
> +    }
또한, 테스트 코드를 가동할 때도 만약 CharacterRepository 안에 DB의 내용이 저장된 후에 돌아가게 된다면 해당 테스트가 실패할 가능성이 있다고 생각하는데, 이에 대해서는 어떻게 생각하시나요?

2024-07-22 02:09 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/ModifyCharacterRequest.java
> +public record ModifyCharacterRequest(String modelType, String name, URL selectionThumbnailUrl) {
캐릭터를 modify하는 경우에는 id를 받은 후에 그에 대한 name 혹은 selectionThumbnailUrl을 수정하는 로직이 더 좋을 것 같은데 어떻게 생각하시나요?

2024-07-22 02:09 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/service/CharacterService.java
> +    public CharacterResponses showCharactersByModelType(String modelType) {
modelType별로 캐릭터 정보를 받도록 설계할 예정이라면, 해당하는 이유가 무엇인지 궁금합니다.

현재 저희의 어플리케이션 설계 상 캐릭터들 정보가 필요한 경우는 어플리케이션에서 캐릭터 정보를 선택할 때 만인데,
이러한 형태로 가게 된다면 어플리케이션에서는 DallE, Midjourney, Stable Diffusion에 대한 모델 정보를 다 따로 제공해야 하나요?

+ 유저 입장에서는 캐릭터를 모델 별로 구분하였다는 느낌보다는 '작품' 별로 구분하였다는 느낌을 주는 것이 더 좋을 듯 합니다..!
따라서 Character에 어떤 작품의 것인지를 넣는 부분이 필요할 듯 합니다.

2024-07-22 07:36 UTC, minseojo commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterRepositoryTest.java
> +    }
> 또한, 테스트 코드를 가동할 때도 만약 CharacterRepository 안에 DB의 내용이 저장된 후에 돌아가게 된다면 해당 테스트가 실패할 가능성이 있다고 생각하는데, 이에 대해서는 어떻게 생각하시나요?

이 부분을 고려해서 


15번쩨 줄 @ActiveProfiles("test")
을 이용해서 새로운 yml 파일을 만들어 테스트 전용 DB를 만들어서 고려했습니다.

2024-07-22 07:36 UTC, minseojo commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/character/domain/CharacterRepositoryTest.java
> +    }
> 실패 테스트 코드도 작성해야 할 것 같다고 생각합니다..!
> 
> ex. 어떤 캐릭터를 찾을 수 없는 경우

넵!

2024-07-22 07:39 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/dto/request/ModifyCharacterRequest.java
> +public record ModifyCharacterRequest(String modelType, String name, URL selectionThumbnailUrl) {
저는 민준님이 짰던 코드인

selectionThumbnailUrl의 자료형 String -> URL 변경
필요 없는 필드 calendarThumbnailUrl  제거
를 한거라서.. 다 같이 이야기 해봅시다.

근데 저도 Id를 받아서 수정하는게 좋다고 생각합니다!

2024-07-22 07:42 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/service/CharacterService.java
> +    public CharacterResponses showCharactersByModelType(String modelType) {
일기 작성 후, 캐릭터 선택 페이지에서
DallE(랜덤), Midjourney(캐릭터), Stable Diffusion(작화-작화에 대한 캐릭터)에 대한 모델 타입 버튼을 각 따로 선택해서 해당하는 모델 정보를 따로 제공 해주기에 이렇게 했습니다.

하지만 처음부터 클라이언트에게 전부 다 모델 정보를 상태로 제공하고 캐릭터가 선택한 타입에 맞춰 보여주는 것이 효율적인 것 같네요.

2024-07-23 06:46 UTC, SproutMJ approved these changes
확인 했습니다. 준교님이 언급한 부분만 수정하면 좋을 것 같아요

2024-07-23 07:27 UTC, JuneBridge03 approved these changes

2024-07-23 07:28 UTC, merged