feat: 멤버 정보 조회, 수정, 탈퇴 api 구현 및 테스트 코드 작성
software-maestro-starting-blue/fourtoon-cookie-backend pull request #28
Opened 2024-07-28 06:37 UTC by minseojo

# [feat] 멤버 정보 조회, 수정, 탈퇴 api 구현 및 테스트 코드 작성
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-
---
### 구현 내용
- 멤버 정보 조회, 수정, 탈퇴 api 구현 및 테스트 코드 작성

2024-07-28 07:43 UTC, SproutMJ approved these changes
확인했습니다!

2024-07-29 12:25 UTC, JuneBridge03 requested changes
좋은 코드 작성해주셔서 감사합니다..!

다만, 놓치신 부분들이 있으신 것 같아서 코멘트를 남겼습니다!

+ 또한, 현 branch에 현재의 commit과 과거의 commit이 섞인 듯 하여서 추후 dev 브랜치에서 코드 관리를 할 때 악영향이 갈 것 같아 우려스럽습니다.

2024-07-29 12:25 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberExceptionControllerAdvice.java
> +@RestControllerAdvice
패키지 지정을 해야 할 듯 합니다..!

2024-07-29 12:25 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/service/MemberService.java
> +    }
이미 findById가 동일 역할을 수행하는 듯 합니다..!

2024-07-29 12:25 UTC, JuneBridge03 commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
> +        when(memberRepository.findById(memberId)).thenReturn(Optional.of(member));
이 친구는 Mocking으로 상황을 설정하는 과정이어서 when보다는 given인 것 같고 오히려 현 56번째 줄의 코드가 when인 것 같은데 어떻게 생각하시나요..?

2024-07-29 12:25 UTC, JuneBridge03 commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
> +        when(memberRepository.save(member)).thenReturn(member);
이 친구는 Mocking으로 상황을 설정하는 과정이어서 when보다는 given인 것 같은데 어떻게 생각하시나요..?

2024-07-29 12:25 UTC, JuneBridge03 commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
> +    }
given when then 패턴을 명시하면 좋을 듯 합니다..!

2024-07-29 17:47 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/MemberController.java
> +@RequiredArgsConstructor
넵..!

2024-07-29 17:47 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/member/exception/MemberExceptionControllerAdvice.java
> +@RestControllerAdvice
넵..!

2024-07-29 17:48 UTC, minseojo commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
> +        when(memberRepository.findById(memberId)).thenReturn(Optional.of(member));
given이 맞는 것 같습니다

2024-07-29 17:48 UTC, minseojo commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
> +        when(memberRepository.save(member)).thenReturn(member);
given이 맞는 것 같습니다

2024-07-29 17:48 UTC, minseojo commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/member/service/MemberServiceTest.java
> +    }
넵~

2024-07-29 17:48 UTC, minseojo commented
> 좋은 코드 작성해주셔서 감사합니다..!
> 
> 다만, 놓치신 부분들이 있으신 것 같아서 코멘트를 남겼습니다!
> 
> * 또한, 현 branch에 현재의 commit과 과거의 commit이 섞인 듯 하여서 추후 dev 브랜치에서 코드 관리를 할 때 악영향이 갈 것 같아 우려스럽습니다.

음 그러게요 브랜치를 하나 새로 파는게 나을 것 같네요

2024-07-31 05:06 UTC, closed without merging

2024-07-31 05:07 UTC, minseojo commented
리베이스로 인한 코드 혼란성으로 해당 풀리퀘는 머지하지 않았습니다.