[feat] 캐릭터 추가, 수정, 삭제, 전체 조회 api 구현
software-maestro-starting-blue/fourtoon-cookie-backend pull request #3
Opened 2024-07-10 07:29 UTC by SproutMJ

# [feat] 캐릭터 추가, 수정, 삭제, 전체 조회 api 구현
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-154
---
* 구현 내용
캐릭터 추가 api

* 추가 발생한 문제(논의 사항)
### TSK-157
---
* 구현 내용
캐릭터 수정 api
put이므로 수정하지 않는 부분도 전체 값을 모두 입력해야 함

* 추가 발생한 문제(논의 사항)
* ### TSK-155
---
* 구현 내용
캐릭터 삭제 api
soft delete가 아니므로 db에서 완전 제거됨

* 추가 발생한 문제(논의 사항)
* ### TSK-181
---
* 구현 내용
캐릭터 전체 조회 api

* 추가 발생한 문제(논의 사항)
일단은 전체 조회로 구현했는데 ui 상 모델별로 보여준다면 전체 조회하고 ui 상에서 분류해서 보여주면 될 수도 있습니다.
근데 다른 방법도 있을법합니다.

2024-07-12 16:14 UTC, JuneBridge03 requested changes
좋은 코드 짜주셔서 너무 감사합니다~! 많이 배웁니다.

다만, 조금 논의해야 할 부분이 있는 것 같아서 일단 Request changes를 드립니다...!

감사합니다!

2024-07-12 16:14 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/domain/ModelType.java
> +    public static ModelType from(final String value){
오.. 이건 진짜 순수한 궁금증이긴 한데, 이러한 역할을 하는 함수명은 보통 from이라고 짓나요..? 만약에 그렇다면 이유가 있는지가 궁금하네요..!!

2024-07-12 16:18 UTC, minseojo approved these changes

2024-07-15 10:05 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/character/controller/CharacterController.java
> +    public ResponseEntity<HttpStatus> modifyCharacter(@PathVariable final Long characterId) {
와우 말되안되는 이슈네요 고쳤습니다

2024-07-18 18:26 UTC, JuneBridge03 approved these changes
좋은 코드 확인했습니다~

2024-07-21 05:44 UTC, merged