feat & refactor: Diary 관련 클래스 검증 추가 및 리팩토링
software-maestro-starting-blue/fourtoon-cookie-backend pull request #37
Opened 2024-07-31 22:22 UTC by minseojo

# [feat & refactor] Diary 관련 클래스 검증 추가 및 리팩토링
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [x] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-256
---
* 구현 내용
* feat & refactor: Diary 관련 클래스 검증 추가 및 리팩토링

* 추가 발생한 문제(논의 사항)
`@NotEmptyList` 검증 어노테이션 생성 -> 최상위 패키지.validator

2024-07-31 22:24 UTC, minseojo commented
다이어리 클래스는 컨트롤러가 변경 될 예정 (memberId 관련)

2024-08-03 06:40 UTC, SproutMJ requested changes

2024-08-03 06:40 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/exception/DiaryExceptionControllerAdvice.java
>  @RestControllerAdvice("com.startingblue.fourtooncookie.diary")
여기서 전부 e.getMassage를 반환하고 있는데, 클라이언트에 가기에 구체적인 정보들이 들어갈 것 같습니다.

2024-08-03 06:40 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public void verifyUniqueDiaryEntry(UUID memberId, LocalDate diaryDate) {
private가 되지 않아도 괜찮을까요?

2024-08-04 05:40 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public void verifyUniqueDiaryEntry(UUID memberId, LocalDate diaryDate) {
반영했습니다~

2024-08-04 05:57 UTC, SproutMJ approved these changes

2024-08-04 08:48 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public List<Diary> readDiariesByMember(final UUID memberId, final int pageNumber, final int pageSize) {
readDiariesByMemberId가 더 적합해보이는데 어떻게 생각하시나요..?

2024-08-04 08:48 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public void toggleFavoriteDiary(Long diaryId, boolean isFavorite) {
toggle은 "전환"을 의미하는 용어여서 차라리 다른 용어로 함수명을 바꾸는 것은 어떠신가요?

2024-08-04 08:48 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public Diary findById(final Long id) {
CRUD를 따르기로 하여서 readById가 더 괜찮을 것 같습니다..!

2024-08-04 10:19 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public void toggleFavoriteDiary(Long diaryId, boolean isFavorite) {
우선 일관성있게 `updateDiaryFavorite` 으로 변경했습니다

2024-08-04 10:19 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public List<Diary> readDiariesByMember(final UUID memberId, final int pageNumber, final int pageSize) {
넵 변경했습니다

2024-08-04 10:19 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +    public Diary findById(final Long id) {
넵!

2024-08-04 10:19 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
>      }
넵 해당 메서드는 지웠습니다.

2024-08-04 12:20 UTC, JuneBridge03 approved these changes
코드리뷰 잘 반영된 것 확인하였습니다! 수고해주셔서 감사합니다.

2024-08-04 12:24 UTC, merged