feat: 일기, 이미지, 해시태그 관련 기능 추가
software-maestro-starting-blue/fourtoon-cookie-backend pull request #4
Opened 2024-07-12 11:58 UTC by minseojo

# [feat] 일기, 이미지, 해시태그 관련 기능 추가
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-151, TSK-179, TSK-182

2024-07-15 08:03 UTC, JuneBridge03 requested changes

2024-07-15 08:03 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/service/PaintingImageService.java
> +        uploadPaintingImageS3(foundDiary, paintingImageSaveRequest.paintingImageUrls());
imageUrl은 S3에 이미 올려진 url인지의 여부가 궁금해집니다.

1. 만약 imageUrl이 S3에 이미 올려진 url이 맞다면, 굳이 다시 S3에 이 내용을 저장하는 이유를 모르겠습니다.
2. 만약 imageUrl이 S3에 올려지지 않은 url이라면, 해당 url을 저장하고 있는 곳은 어디인지가 의문입니다.

물론 DallE라면 이러한 방법이 맞을 수는 있으나, Midjourney 혹은 StableDiffusion을 활용하게 된다면 이 로직은 임시방편적인 로직이 될 것 같아서 우려스럽습니다.

2024-07-15 08:04 UTC, JuneBridge03 requested changes
매우 많은 로직을 관리하시기 부담스러우셨을 텐데도 철저하게 관리해주셔서 감사합니다.

다만, 놓치신 부분들이 몇가지 있는 것 같아서 해당 부분에 대한 수정 요청을 올려드리니 확인 후 수정해주시면 감사하겠습니다.

2024-07-15 09:00 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/HashtagController.java
> +}
아직 인증절차가 없어서 인증관련 코드를 도입하면 모든 컨트롤러 코드를 변경해야 할 것 같기는 합니다.

현재 Hashtag에 대해서 는 admin만 요청을 하기는 하지만 이것의 이름을 HashtagAdminController 이런식으로 변경한다면 컨트롤러가 너무 구체화 되는 것 같습니다. 
같은 맥락으로 Diary에서 사용자가 일기를 쓰고 몇 시간 이후에 이미지가 생성되면 ai 코드에서 Diary 컨트롤러로 요청을 보낼테고, 컨트롤러는 이 요청을 받아서 해당 이미지를 변경하는 로직이 추가될 텐데 그럼 이것의 컨트롤러 DiaryAdminController 로 따로 만들어야 할 것 같은데.. 음 조금 더 고민해보겠습니다.

2024-07-15 09:02 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/Hashtag.java
> +@NoArgsConstructor
이것은 (access = AccessLevel.PROTECTED)로 막는게 맞는데 모르고 지운것 같습니다!
기본 생성자는 JPA 에서 내부적으로 이용해야해서 private으로 막지는 못합니다.

2024-07-15 09:03 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
> +        log.info("favorite: {} diary {}", isFavorite, diaryId);
log는 해야할 것 같은데 log 가 필요한 부분은 따로 이야기 해봐야 할 것 같습니다.

일단 이부분은 지우겠습니다!

2024-07-15 09:07 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java
> +    }
크게 public, private 메서드 순서대로 정렬해두었고,
add, remove, has 순서대로 정렬하겠습니다!
그리고 add, remove  등에 대해서는 (복수, 단수) - 복수가 앞에 오도록 정렬 해 놓을게요
이거는 따로 이야기 해봅시다.

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +//                .orElseThrow(() -> new RuntimeException("Character with ID " + diarySaveRequest.characterId() + " not found"));
구현되지 않은 부분이 너무 많아서 노션 백로그 페이지에 적어두기는 했는데 TODO 도 적어놓겠습니다..!

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +                        PageRequest.of(request.pageNumber(), request.pageSize(), Sort.by(Sort.Direction.DESC, "createdAt")))
diaryDate가 중간에 생겨서 고치지 못한것 같네요 diaryDate 기준이 좋은 것 같은데
우선은 diaryDate 기준으로 해놓을게요~

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/HashtagFactory.java
> +//    }
새로운 해시태그 음식 등등이 추가 될 경우에는 필요하기는 한데, 이런 경우에는 아마 서버 자체를 껐다 킬거라고 이야기가 나왔던것 같아서 우선 주석처리 해두었습니다.

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/HashtagFactory.java
> +}
```java
public void createHashtag(HashtagSaveRequest request) {
        // ...
        Hashtag createdHashtag = HashtagFactory.create(
                request.hashtagName(),
                HashtagType.from(request.hashtagType())
        );
        hashtagJpaRepository.save(createdHashtag);
        hashtagInMemoryRepository.save(createdHashtag);
    }
```

HashtagService코드 중 일부분 입니다.

예를 들어, 감정 해시태그에 [기쁨, 슬픔] 이 있었고 동적으로 화남을 추가하려면 
해시태그 이름: "화남",
해시태그 타입: "감정" 이라는 타입이 필요한데
해시태그 타입에는 감정, 만난사람, 날씨 + 음식등이 추가 될 예정 이기 때문에 이 부분을 if문이 아닌 동적으로 추가 될 수 있게끔 만들었습니다. 또한 이렇게 하면 새로운 구현체가 생길때마다 서비스 로직은 변경되지 않고 새로운 해시태그타입 클래스만 만들어서 확장이 가능하기 때문에 OCP가 지켜진다고 생각했습니다..!

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/HashtagType.java
> +    }
민준님 따라했습니다..! 아마 팩토리 메소드 명명 패턴에서 가져온 것으로 예상됩니다.

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/repository/HashtagInMemoryRepository.java
> +    }
넵 알겠습니다! 디테일 따봉 드립니다.

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/service/HashtagService.java
> +
결론부터 말하자면 캐싱이 목적이었습니다. 근데 이부분은 나중에 redis 등을 이용해도 좋을 것 같습니다.

다이어리를 조회할 때 클라이언트가 보내준 List<hashtagIds>에 대해서 해시태그 정보들을 보내줘야 하는데, 매번 네트워크를 타고 디비를 들어가는 것 보다 인메모리에 해시태그들을 적재해두고 네트워크를 안타는게 효율적일 것 같아서 이렇게 구현했습니다.

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/PaintingImageController.java
> +}
실수인 것 같습니다!

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/dto/PaintingImageSaveRequest.java
> +}
음 클라이언트의 요청에 대해서 어떻게 판별해서 처리해야할 지 이야기 해봐야할 것 같습니다.

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/service/PaintingImageService.java
> +        uploadPaintingImageS3(foundDiary, paintingImageSaveRequest.paintingImageUrls());
로컬에 이미지를 저장해도 되지만 최종적으로 S3를 이용해서 우선 임시방편으로 짜놓은 코드가 맞습니다..
이 부분도 다음 스프린트때 같이 이야기 해봐야할 것 같습니다

현재 PaintingImage 패키지 내용은 하나도 이용되지 않습니다.

2024-07-15 09:35 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/DiaryHashtag.java
> +}
네 이 다대다 매핑 테이블 부분을 어떤 패키지에 둬야할 지 같이 이야기 해봐야할 것 같습니다.

2024-07-15 09:38 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/HashtagController.java
> +}
인증절차는 분리를 해서 컨트롤러나 서비스가 알지 않도록(필터에서 걸러내는 경우 필터를 통과하면 인가가 완료된 것으로 간주하고 컨트롤러에서 작동) 하면 그냥 구현을 해도 될것같은데 어떻게 생각하시나요?
키워드는 인터셉터, 필터, 알규먼트 리졸버 등이 사용될 것 같아요.

2024-07-15 09:39 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
> +        log.info("favorite: {} diary {}", isFavorite, diaryId);
네 log 정책은 아직 없어서 이후에 정해보는 것이 좋겠네요

2024-07-15 09:40 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java
> +    }
보통 읽는 순서=작동 순서로 하면 가독성이 좋아지긴 합니다.

2024-07-15 09:42 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/HashtagType.java
> +    }
valueOf로 할려했는데 이미 먹혀서 인자를 하나 받는 경우인 from으로 했던 것 같아요.
https://velog.io/@saint6839/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EB%84%A4%EC%9D%B4%EB%B0%8D-%EB%B0%A9%EC%8B%9D
보면 좋을 것 같습니다.

2024-07-15 09:49 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/HashtagController.java
> +}
넵 좋습니다!
컨트롤러가 변경된다는 점은 매개변수에 인증된 멤버를 가져오고 찾기 위해서 `HttpServletRequest httpRequest` 가 추가 되거나 공통 로직으로 묶어서 그 해당 코드를 추가하기는 해야 할 것 으로 예상했었는데 이게 아니고, 컨트롤러를 아예 안바꿔도 가능한가요?
찾아보니 AOP 관련 내용이 나오기는 하네요

2024-07-15 09:51 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java
> +    }
public 과 private을 굳이 구분했었는데 작동 순서로 해도 좋을 것 같네요!

2024-07-15 09:55 UTC, SproutMJ approved these changes
구현에 고민을 많이 하신게 느껴졌던 코드였습니다.
사실 준교님의 리뷰 퀄리티가 좋아 저는 간단하게 스타일 정도만 남기고 가겠습니다..

2024-07-15 09:55 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
> +        diaryService.createDiary(request, 1L); // TODO : 우선 디폴트 값 넣어 놓음.
여기도 디폴트값이 있긴 한데요 혹시 추가 구현이 필요한 부분인가요?

2024-07-15 09:55 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
> +        List<DiarySavedResponse> responses = diaryService.readDiariesByMember(diaryPageRequest, memberId);
페이징에 필요한 매개변수를 바로 Integer가 아닌 dto로 넘겨주는 이유가 있을까요?
새로 시행된 정책이었던건지 궁금하네요

2024-07-15 09:55 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/exception/DiaryExceptionControllerAdvice.java
> +    }
생각해보니 저희 error response가 없네요

2024-07-15 09:55 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/service/PaintingImageService.java
> +        for (int imageCount = 0; imageCount < imageUrls.size(); imageCount++) {
enhanced for를 사용해보면 어떨까요

2024-07-15 09:55 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/service/PaintingImageService.java
> +            final String uploadPath = paintingImageFolder + diary.toString() + ".jpg";
.jpg와 아래의 image/*는 아래에서도 사용되는 듯 한데 상수화를 하는 것에 대해 어떻게 생각하시나요

2024-07-15 09:57 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/service/PaintingImageService.java
> +        for (int imageCount = 0; imageCount < imageUrls.size(); imageCount++) {
어 그렇네요!

2024-07-15 09:57 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/service/PaintingImageService.java
> +            final String uploadPath = paintingImageFolder + diary.toString() + ".jpg";
좋습니다! 많이 놓친 것 같습니다 ㅠ

2024-07-15 09:58 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
> +        List<DiarySavedResponse> responses = diaryService.readDiariesByMember(diaryPageRequest, memberId);
나중에 무한스크롤 관련과 같이 페이징 부분에서 처리가 늘어날 것 같아서 dto로 따로 만들어 두었습니다.

2024-07-15 09:59 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
> +        diaryService.createDiary(request, 1L); // TODO : 우선 디폴트 값 넣어 놓음.
member관련 코드가 없었어서 제가 임의로 기본 값 넣어둔 것 같습니다. 수정하겠습니다~~

2024-07-16 04:08 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/DiaryController.java
> +        List<DiarySavedResponse> responses = diaryService.readDiariesByMember(diaryPageRequest, memberId);
다시 보니 validation 패키지 이용하면 될 것 같아서 dto는 없애고 페이징에 필요한 매개 변수 바로 넘기겠습니다!

2024-07-16 04:11 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/image/paintingimage/service/PaintingImageService.java
> +        for (int imageCount = 0; imageCount < imageUrls.size(); imageCount++) {
아 이 부분 `final String uploadPath = paintingImageFolder + diary.getId() + "[" + imageCount + "].jpg";` 에서 imageCount를 출력하려고 이렇게 했었는데 enhanced for 사용해서 그에 맞춰서 코딩하겠습니다!

2024-07-16 10:33 UTC, minseojo commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/hashtag/domain/HashtagFactory.java
> +}
해시태그 같은 경우 추 후 에도 상수로만 관리될 것 같다는 회의내용을 반영해서 클래스 형태가 아닌 상수 형태로 코드 반영했습니다!

2024-07-18 18:32 UTC, JuneBridge03 approved these changes

2024-07-18 18:33 UTC, merged